export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Products } from './Products';
export { default as SellerDetailOrder } from './SellerDetailOrder';
export { default as SellerOrders } from './SellerOrders';
export { default as CustomerDetailOrder } from './CustomerDetailOrder';
export { default as CustomerOrders } from './CustomerOrders';
export { default as Checkout } from './Checkout';
export { default as Admin } from './Admin';
